version: "3"
services:
    attacker:
        build: 
            context: .
            dockerfile: attacker.Dockerfile
        image: attacker:latest
        privileged: true
    victim:
        build: 
            context: .
            dockerfile: victim.Dockerfile
        image: victim:latest
