version: "3"
services:
    attacker:
        build: 
            context: .
            dockerfile: attacker.Dockerfile
        image: attacker:latest
        cap_add: 
            - NET_RAW
            - NET_ADMIN
    victim:
        build: 
            context: .
            dockerfile: victim.Dockerfile
        image: victim:latest
